spring.application.name=marketing-agency-backend

spring.server.url=

############# LOCAL CONFIGURATION #########

server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/Caryanam_Marketing?createDatabaseIfNotExist=true&useSSL=true
spring.datasource.username=root
spring.datasource.password=swapnil@182


# =========================================
# MySQL Configuration
# =========================================

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# =========================================
# JWT Security Configuration
# =========================================

security.jwt.secret=kefkefnenfenfssssenfnefefnefvbnenfewfnefnefnefnenfenfenfewjnfewnfewnfewfln
security.jwt.expiration=86400000


# =========================================
# Email Service Configuration (Hostinger SMTP)
# =========================================
spring.mail.host=smtp.hostinger.com
spring.mail.port=465
spring.mail.username=support@caryanam.com
spring.mail.password=Kharadi@6006
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
